# Generated by Django 5.2.7 on 2025-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(default="noemail@gmail.com", max_length=254),
                ),
                ("password", models.CharField(max_length=128)),
                ("confirm_password", models.CharField(max_length=128)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
