# Generated by Django 5.2.7 on 2025-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Age", models.IntegerField(max_length=3)),
                ("Gender", models.BooleanField()),
                ("Department", models.CharField(max_length=100)),
                ("Time", models.TimeField()),
                ("Date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
    ]
