# Generated by Django 5.2.7 on 2025-10-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking_model",
            name="Gender",
        ),
        migrations.AddField(
            model_name="booking_model",
            name="Female",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking_model",
            name="Male",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking_model",
            name="Age",
            field=models.IntegerField(),
        ),
    ]
