# Generated by Django 5.2.7 on 2025-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0002_remove_booking_model_gender_booking_model_female_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("message", models.CharField()),
            ],
        ),
    ]
