# Generated by Django 5.2.7 on 2025-10-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0003_message_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="message_model",
            name="email",
            field=models.EmailField(default="noemail@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="message_model",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message_model",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
