# Generated by Django 5.2.7 on 2025-10-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0004_message_model_email_alter_message_model_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message_model",
            name="email",
            field=models.EmailField(
                blank=True, default="noemail@example.com", max_length=254, null=True
            ),
        ),
    ]
