# Generated by Django 5.2.7 on 2025-10-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0005_alter_message_model_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message_model",
            name="phone",
            field=models.CharField(max_length=30),
        ),
    ]
